name: Build & Test
env:
  SDK_ALCHEMY_KEY: ${{ secrets.SDK_ALCHEMY_KEY }}

on: [push, pull_request]
jobs:
  tests:
    name: "Build against Go ${{ matrix.os }}"
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build
        run: go build -v ./web3sdks

      - name: Test
        run: yarn add hardhat && make test

